### ISSUE TITLE
How to use this in MainAcitivity of android project

### ISSUE THREAD

**Issue by manpreetsinghsodhi** [telamon/Android-Ajax.Request#1]
I have ajax request in following form and i need to get its response in my android app 

var request = {};
request.UserName = "some data"; // this should be always hard coded like this 
request.Password = "some data";  // this should be always hard coded like this
request.CurrentUsername = "admin"; //   this is hard coded like this for now 

request.FirstName = "some data";
request.LastName = "some data";

var send = {};
send.request = request;
$.ajax({
    type: "POST",
    contentType: "application/json; charset=utf-8",
    url: "some link",
    data: JSON.stringify(send),
    dataType: "json",
    async: false,
    success: function (msg) {
        // Process the result here
    },
    error: function () {
        //alert("error");
        // Display the error here in the front end
    }
});
});
});

I have no knowledge about ajax so i found your github tutorial on this. I imported it and found two classes Transport.java and Request.java . Please guide me how to use them in MainActivity of my android project.
Thanks

**Comment by telamon** [comment]
Hey!

To be honest wth you, I wrote that code over four years ago. And by
accident i had actually mixed up the whole terminology in my head since
there's actually no "AJAX" occurring inside an Android appliction. ( The
AJAX term exclusively describes the XHR techique in a web-browser that
enables you to make additional web-requests in the background without
reloading the whole page)

So what you probably want, and what i wanted  all those years ago was to do a google
search for "Android HTTP REST request" because we can completely skip the
"ajax/xhr"  and just focus on communication with the
REST API . So I could **NOT** recommend that you use my request-wrapper as android has changed
alot in the past years.
